### ISSUE TITLE
Tryjob results say 'No changed test results' when they are some in race condition

### ISSUE THREAD

**Issue by sortie** [dart-lang/dart_ci#51] opened 2019-12-16 13:37 UTC
The tryjob results page will erroneously display 'No changed test results' momentarily while it actually fetches the test results, misleading the user for a moment. It should say 'Loading' instead and only conclude there's no changed test results when they've actually been loaded.

Example: https://dart-ci.firebaseapp.com/cl/127465/1

**Comment by athomas** [comment] 2020-03-30 09:52
Dupe of https://github.com/dart-lang/dart_ci/issues/84.

**Closed by athomas** 2020-03-30 09:52 UTC
